# Site settings
title: Fernando Silveira
email: fsilveira@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Here you can find my personal software projects and development experiences
  I like to share.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://swrh.github.io" # the base hostname & protocol for your site
twitter_username: swrh
github_username:  swrh
linkedin_username: fgsilveira
aboutme_username: swrh

# Build settings
markdown: kramdown
