# Site settings
title: Fernando Silveira
email: fsilveira@gmail.com
description: a.k.a. <a href="https://twitter.com/swrh" target="_blank">@swrh</a>
baseurl:
url: https://swrh.github.io
twitter_username: swrh
github_username:  swrh
linkedin_username: fgsilveira
aboutme_username: swrh

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
